services:
  #  server:
  #    container_name: 'server'
  #    build: .
  #    #    When using M1
  #    platform: linux/amd64
  #    #      dockerfile: 'Dockerfile'
  #    image: 'server:latest'
  #    ports:
  #      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
#      - ./postgresql-data:/var/lib/postgresql/data
      - ./postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
      - ./postgresql-populate.sql:/docker-entrypoint-initdb.d/postgresql-populate.sql

  rabbitmq:
#    image: rabbitmq:latest
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
